


### Security Requests



###
GET /api/v1/security/csrf-token
Host: localhost:9000
Accept: application/json

###
GET /api/v1/security/login
Host: localhost:9000
Accept: text/plain
Authorization: Basic zagor@gmail.com zagor

###
GET /api/v1/security/logout
Host: localhost:9000
Accept: text/plain



### Identity Requests



###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 2wkOyNGfFWXklgVeodLduMuDMa0BWBN9QSi9ncICy4NoEbQO7zFq_uanIlXJpzM7lP_piK-0HJUyPHVQJR3Yr_Bn_bRZddA6

{
    "authority": "ADMIN",
    "email": "burgasvv@gmail.com",
    "password": "burgasvv",
    "status": true,
    "firstname": "Бургас",
    "lastname": "Вячеслав",
    "patronymic": "Васильевич",
    "about": "Коротко о личности"
}

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: noBydo5WtKLr9QhHSAswEDayuubb_P7VahVVmobHjYuhhIbU_LdATuhn0MTGxG5-cCYEIQPUl4Tjmcj4XHNh_rD37rOSveTg

{
    "authority": "USER",
    "email": "zagor@gmail.com",
    "password": "zagor",
    "status": true,
    "firstname": "Загорулько",
    "lastname": "Борис",
    "patronymic": "Юрьевич",
    "about": "Коротко о личности Загорулько Бориса Юрьевича"
}

###
POST /api/v1/identities/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: dMZpBpy7dXryX9AXRrUo0EDcbPsq2PoRF2yKemslACuRaO3-QP4NMKuDQkrfbuZyc5gc4CTrQcMZvJw8c1nvSFlANhygDInK

{
    "id": "765b8d61-8299-4a54-8b59-fe21b6ce7532",
    "about": "Коротко о личности Бургаса Вячеслава Васильевича"
}

###
GET /api/v1/identities
Host: localhost:9000
Accept: application/json

###
GET /api/v1/identities/by-id?identityId=765b8d61-8299-4a54-8b59-fe21b6ce7532
Host: localhost:9000
Accept: application/json

###
DELETE /api/v1/identities/delete?identityId=391a9307-707f-4a5f-999b-5897df571d6a
Host: localhost:9000

###
PUT /api/v1/identities/change-password
Host: localhost:9000
Content-Type: application/json
X-Csrf-Token: d1TMnZSQzVnMS7XtDX5ApuZw4cxt9glkyH3-gi8AmgB8DARSFmH4-_L2qWjhe9bZOVN0ldUSzK4OkD9J-hnNsxxl_DZJPzJg

{
    "id": "765b8d61-8299-4a54-8b59-fe21b6ce7532",
    "password": "burgasvv"
}

###
PUT /api/v1/identities/add-course?identityId=8a00a975-7f7e-469d-91fd-98fb4e217d84&courseId=8efdfbac-88b5-4b79-86c6-b10f04bf45e0
Host: localhost:9000
Accept: application/json
X-Csrf-Token: R3-Qkn1Zrl9GTAWheCjP6xG24w7OsxoqY13_HBfsDreW35DKJBmhp004ym5rejOUHgX73nWDzmyohi4HUm6eL3PZOYSg5qb8



### Course Requests



###
POST /api/v1/courses/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: yRN3Ts59uoDbqhBCdtdUqZWPnn7x7hu17k59pT1sa-g9P1BwqnVGe_4c3rH2nCZ3EPpgnPG6sxyX2y-Y330clllZXNsLBmZG

{
    "name": "Java Course",
    "description": "Описание курса Java Course"
}

###
POST /api/v1/courses/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
X-Csrf-Token: yRN3Ts59uoDbqhBCdtdUqZWPnn7x7hu17k59pT1sa-g9P1BwqnVGe_4c3rH2nCZ3EPpgnPG6sxyX2y-Y330clllZXNsLBmZG

{
    "id": "45be50de-743b-443f-b829-95ef7e11149f",
    "description": "Описание курса Java Course для студентов"
}

###
GET /api/v1/courses
Host: localhost:9000
Accept: application/json

###
GET /api/v1/courses/by-id?courseId=8efdfbac-88b5-4b79-86c6-b10f04bf45e0
Host: localhost:9000
Accept: application/json

###
DELETE /api/v1/courses/delete?courseId=45be50de-743b-443f-b829-95ef7e11149f
Host: localhost:9000
X-Csrf-Token: yRN3Ts59uoDbqhBCdtdUqZWPnn7x7hu17k59pT1sa-g9P1BwqnVGe_4c3rH2nCZ3EPpgnPG6sxyX2y-Y330clllZXNsLBmZG